### ISSUE TITLE
Add additional search areas

### ISSUE THREAD

**Issue by DVRPCfreight** [DVRPCfreight/TrafficCountConcept#1]
Currently only provides for search areas from DVRPC municipality database.

Add features including:
- Zip codes
- Philadelphia neighborhoods
- Places

**Comment by crvanpollard** [comment]
Need to publish AGS feature service of zip code boundaries and Philadelphia neighborhoods

**Comment by seandoesgis** [comment]
No need to publish

Philly neighborhoods (Azavea)
http://services.arcgis.com/rkitYk91zieQFZov/ArcGIS/rest/services/Philadelphia_Neighborhoods/FeatureServer/0

Zip codes (ESRI)
http://services.arcgis.com/P3ePLMYs2RVChkJx/arcgis/rest/services/USA_ZIP_Codes_2014/FeatureServer/0
