### ISSUE TITLE
Limit table to map features

### ISSUE THREAD

**Issue by DVRPCfreight** [DVRPCfreight/TrafficCountConcept#16]
Add functionality that filters the table to show only those elements that are in the map view add any given time.

**Comment by wtsay** [comment]
https://github.com/wtsay/TrafficCountConcept/commit/92811f155fbd595c9382e6aa446c0c89eaa547ee

Filter/sync is toggled on/off via filter glyphicon in a new Leaflet control in top left (red: on, bloo: off).
When on, a subset of TCtable is displayed if the features are not within map bounds.
Filtering is fired on map moveend event.

NoResults modal displays if the map is zoomed/panned out of view of points.
