### ISSUE TITLE
Sorting Data Table by AADT 

### ISSUE THREAD

**Issue by crvanpollard** [DVRPCfreight/TrafficCountConcept#35]
When sorting the data table results by AADT it does not sort the count volumes correctly/in the proper order numerically. Need to have AADT be handled as a numeral instead of an integer.

**Comment by wtsay** [comment]
https://github.com/DVRPCfreight/TrafficCountConcept/commit/f9b2d1626bb5a1756842a466dabead76616dc08b

Demo: http://orephik.com/tcc_f9b2d16
