### ISSUE TITLE
Handle multi-line table rows

### ISSUE THREAD

**Issue by DVRPCfreight** [DVRPCfreight/TrafficCountConcept#38]
Current table build function does not account for multi-line rows causing overflow out of DOM. Requires scrollable DOM element or a modifier to calculate rows that fit in the given space.

**Comment by wtsay** [comment]
Do you have an example or demo?

(Would search/replace new line, carriage return work?)

**Comment by DVRPCfreight** [comment]
Another option could be to create a max character length and then, on mouseover or click, expand the row to show the rest of the information?

They only example I have is a table that build varying number of rows based on DOM pixel space available, which is easy enough to implement. However, it does not adjust for multi-line rows. 
Example is: https://github.com/DVRPCfreight/data-directory

**Comment by wtsay** [comment]
This was a huge pain in the arse.

https://github.com/DVRPCfreight/TrafficCountConcept/commit/4430ce3a5074d27f29e6db9f42dac1080f2eac3b

Demo: http://orephik.com/tcc_4430ce3/

Basically the mixture of DataTable syntax < 1.10 and >= 1.10 was causing issues, so I had to translate everything over to >= 1.10 specification. (Took a while to realise this had to be done)

Now the table is automatically resized on:
- Window resize jQuery listener (height, width via CSS)
- New data added (height only)

**Comment by DVRPCfreight** [comment]
Here is an alternative to the scroll interface. To me it seems odd to have both scroll and pagination for navigating the table.  

2eab3efca53474a694eeb9f1a489b91485686f37

This forces some columns to a max width and when it is reached, it creates an ellipsis and cuts off the excess content. On mouseover of the cell this content reappears. 

In addition, table wrapper height is used to calculate the number of rows that fit in the window and assigned to the dataTables options. This does not yet redraw on window resize.

**Comment by wtsay** [comment]
https://github.com/DVRPCfreight/TrafficCountConcept/commit/995e089ae3e9bae8737720420ba9bd2a50b9c8bb

Small change: Recalculating page length on window resize.

**Comment by crvanpollard** [comment]
@wtsay @DVRPCfreight Is this Data Table issue still a problem?

**Comment by DVRPCfreight** [comment]
@crvanpollard not finished yet. Need to reconcile [995e089](https://github.com/DVRPCfreight/TrafficCountConcept/commit/995e089ae3e9bae8737720420ba9bd2a50b9c8bb) with changes made.

Will revise after #62 is merged.
