### ISSUE TITLE
Provide legend for count types

### ISSUE THREAD

**Issue by DVRPCfreight** [DVRPCfreight/TrafficCountConcept#39]
- Create legend for count types
- Include only those that are searched
- Improve color selection for counts

**Comment by DVRPCfreight** [comment]
Implement legend as toggle for filtering count types in map _(suggestion from 3/18/2016)_

**Comment by wtsay** [comment]
How should the behaviour for the legend filtering work?
Click to enable/disable?
Click to isolate if all are active?
Both?

**Comment by crvanpollard** [comment]
<img width="1239" alt="screen shot 2016-04-09 at 10 51 27 am" src="https://cloud.githubusercontent.com/assets/4401281/14404338/110f3ace-fe41-11e5-857d-6f424204be19.png">

**Comment by crvanpollard** [comment]
@wtsay Branch Test/Pollard modified the layout to work similar to Zillow. Moving Search and Filter buttons out of Data Table container. I would leave map container alone since user really wanted a bigger map in the specs/enhanced requirements.

**Comment by crvanpollard** [comment]
if you work on this over the weekend feel free to Call me (sending you email now with my cell).
One issue you could work on is the 'EXPORT Table Results to CSV'. Don't worry about PDFs for now.

**Comment by crvanpollard** [comment]
This address the 'Include only those that are searched'
Is there a way to check the results table, gather all the different Count Types and pass that arrary to the Count Type filter dropdown list and 'Disable' any Count Types that are not found/displayed in the map/area? 

use case: All the '8 Day' counts are located in NJ, so if a user searches any counts in PA and they go to use the Filter by Count Type they will not be able to check/uncheck the 8 Day counts.

**Comment by DVRPCfreight** [comment]
Fixed by #66
