### ISSUE TITLE
Counts located outside DVRPC region

### ISSUE THREAD

**Issue by crvanpollard** [DVRPCfreight/TrafficCountConcept#47]
Need to include MCD's located outside DVRPC region in the autocomplete 'Search'.
- make sure those MCD's are part of the map service
- add those MCD's to the master .json file
  <img width="621" alt="screen shot 2016-01-26 at 5 02 14 pm" src="https://cloud.githubusercontent.com/assets/4401281/12596678/08252814-c44f-11e5-981a-506f40511c5c.png">

**Comment by DVRPCfreight** [comment]
Could you please define the use case for this, did this request come from Scott?

The query data now lives in the csv rather than a json. Make adjustments in the tc_search_source.xlsx and output an updated csv to the data folder.

**Comment by crvanpollard** [comment]
Have a added Berks County MCDs to search_locations.csv (latest test/pollard branch 4/18/16 #fixes 47)
