### ISSUE TITLE
Marker click functionality: row reorder

### ISSUE THREAD

**Issue by DVRPCfreight** [DVRPCfreight/TrafficCountConcept#5]
Reorder the results table to order the rows based on distance from the click on the map.

**Comment by DVRPCfreight** [comment]
Requires:
- Hidden column for distance from click
- Click for lat/lon 
- Add distance for each feature to hidden column

**Comment by wtsay** [comment]
Are your requirements set in stone?
- No added column (is there a need to save that information?)
- Count coordinates now saved in TCtable objects
- Using JS.array.sort(function(i,j) {}) to calculate Euclidean distances from mouse click, wiping the DataTable and reinserting
  - Leaflet.point.distanceTo takes way too long, although the distance calculation is more precise

https://github.com/wtsay/TrafficCountConcept/commit/c8bfed8a821952c2517c4110bc70376b9a223116

**Comment by crvanpollard** [comment]
Required attributes fields for downloaded data in CSV format (not all fields are shown in table results)
Date of Count,DVRPC File Number, Type, Road, MCD, County, Route Number, Count Direction, From Limit, To Limit, Lat, Long , URL/Link to Detailed Report. This will allow folks to use in Excel or even bring into ArcMap (Display X/Y data), or a web mapping platform (ArcGIS Online, CartoDB, Mapbox).

**Comment by wtsay** [comment]
Right, so saving the distance from mouse click to feature isn't needed. It's just used to sort the table results.

**Comment by DVRPCfreight** [comment]
@wtsay correct the distance field is not necessary, that was just me spit balling possible process. @crvanpollard you are in the wrong issue. That is related to #7 and the downloading of records.

**Comment by crvanpollard** [comment]
whoops, not enough coffee today @DVRPCfreight

**Comment by DVRPCfreight** [comment]
Enhance with a class that styles those count rows that are at the same latlng at click

**Comment by wtsay** [comment]
Somehow DataTables is (magically?) hijacking the background-color CSS property.

https://github.com/wtsay/TrafficCountConcept/commit/0c1199997b7d95c3f5a271803e7ac4af51dd6de7

lib/map.js on line 255 (in the above commit) is where a special tag class gets added to the table row, but only for "even" TR rows does it show up visibly, despite the "odd" TR rows also having the tag class.

Also added in a total search results count only if a subset is being displayed.

**Comment by wtsay** [comment]
Demo:

http://www.orephik.com/tcc_0c11999

**Comment by wtsay** [comment]
https://github.com/wtsay/TrafficCountConcept/commit/06b5b792fc5b23253cf6c2b36037c91e498b8a39

Should be fixed: Turns out the "odd" rows (if table striping is enabled) have the background color set on the TD elements, not the parent TR.

**Comment by DVRPCfreight** [comment]
Fixed but advanced functionality requested in #36 to sort by date in addition to proximity
