### ISSUE TITLE
Add count type definitions

### ISSUE THREAD

**Issue by DVRPCfreight** [DVRPCfreight/TrafficCountConcept#52]
Provide data count definitions to explain to the users the count types.

**Comment by crvanpollard** [comment]
<img width="430" alt="screen shot 2016-03-18 at 11 10 52 am" src="https://cloud.githubusercontent.com/assets/4401281/13882049/1dbda240-ecfa-11e5-9204-ffbfdf43412c.png">

**Comment by DVRPCfreight** [comment]
Create definitions as tool tip on legend items and as modal _(suggestion from 3/18/2016)_

**Comment by wtsay** [comment]
Demo:
http://wololo.co/TCC_71aa017/

**Comment by crvanpollard** [comment]
Speed Counts (from S.Brady) “A vehicle count where volumes are reported in 5 mph speed bins”

**Comment by crvanpollard** [comment]
close #52 --- latest branch of test/pollard (4/18/16)  fixes issue

[admin edit]: @crvanpollard lets not get in the habit of closing branches manually and referencing fixes in this manner. These references should be made through the commits containing changes. As a note, using "fixes #[issue-number]" in commits will close the issue once the commit is merged to master.
