### ISSUE TITLE
Add branding and orientation elements

### ISSUE THREAD

**Issue by DVRPCfreight** [DVRPCfreight/TrafficCountConcept#54]
- [x] Application requires DVRPC consistent theme, logo and any other necessary branding elements.
- [x] Provide orientation for the application users

**Comment by crvanpollard** [comment]
Add some indication to User that they are Viewing Counts for a selected, pre-defined range of years (2011-2016). Possible location:
- Add to Data Table below button for 'View Select Records'  
  or behind the text in the lower left that indicates how many records they are viewing
  <img width="761" alt="screen shot 2016-04-11 at 2 22 45 pm" src="https://cloud.githubusercontent.com/assets/4401281/14437822/065408ec-fff1-11e5-9e9f-d67e1ec0a9c7.png">

**Comment by crvanpollard** [comment]
Need help to indicate to the User the Date/Year Ranges of the Counts that are showing in Table Results. With the years being set to only show the 1st 5 years on initial Search this may cause an issue.

The above image would help address that issue but I have zero working knowledge of DataTables.js
@wtsay @DVRPCfreight @jstrangfeld

**Comment by crvanpollard** [comment]
Joe has assigned Becky from the graphics department to work with us on our branding efforts

**Comment by crvanpollard** [comment]
Suggestion from 4/22/16 meeting w/ J.Ward
<img width="1256" alt="screen shot 2016-04-22 at 5 21 54 pm" src="https://cloud.githubusercontent.com/assets/4401281/14756176/52fdf5fa-08b5-11e6-9be3-7450ef5f9eea.png">
- Modify Draw Tool Help with improved text and possible icons (similar to Map My Run - Create Route tool)

**Comment by DVRPCfreight** [comment]
Not sure I am clear on what we would add beyond the undo and cancel that is already provided? Based on the Map My Run tool box there is only one tool that could be added to the TC application (center), though I am not sure the utility of it given then use case. 

Was there more specificity on what exactly was missing/lacking from the TC draw tool?

**Comment by crvanpollard** [comment]
**TC Draw Tool.**..More consistent and clear text to the user to 'Draw on the Map'.. 
Match the Help text with the text in the buttons....
Such as: 'Cancel Drawing' might be better as 'Clear polygon (or drawing)'
'Undo Las't = 'Undo Last Point'

Also 'Draw Search Area' might be better with the word 'Re-draw'?? or 'Create/Draw custom search Area'?

**Launch Page**: 'Draw Your own area of interest' = 'Draw on the Map' or something like this with the word Map.. When a user comes to the Launch Page they may not know that they will be using a Map to view Traffic Counts so let's make sure they do...

**Comment by seandoesgis** [comment]
How about branding the app with **BETA**?

**Comment by crvanpollard** [comment]
@DVRPCfreight besides adding logo and title to launch and nav bar, do you want additional style changes to buttons and other design elements using color scheme? 
<img width="796" alt="screen shot 2016-06-09 at 7 24 22 am" src="https://cloud.githubusercontent.com/assets/4401281/15928186/75290844-2e13-11e6-86c7-9512a39994c8.png">

**Comment by DVRPCfreight** [comment]
@crvanpollard yes all elements should be updated to reflect the new color scheme

**Comment by crvanpollard** [comment]
@DVRPCfreight do you see any other items in this issue that need to be fixed before BETA launch?
Can we close this issue?

**Comment by crvanpollard** [comment]
fixed #54
