### ISSUE TITLE
fix Capitalization with Road Prefixes and Direction

### ISSUE THREAD

**Issue by crvanpollard** [DVRPCfreight/TrafficCountConcept#57]
- example: Direction is showing up as 'Eb' 'Sb' and both should be  'EB' and 'SB'
- Prefix has 'Us 130' should be 'US 130'

**Comment by DVRPCfreight** [comment]
Cannot replicate. Please specify where this issue is occurring (table, report, etc.). Is this issue browser specific?

Current table shows as capitalized. 
![image](https://cloud.githubusercontent.com/assets/8495073/14147819/fe6aea68-f66a-11e5-883d-0a301174f0b2.png)

**Comment by DVRPCfreight** [comment]
Issue is related to database value to JavaScript formatted value. Requires a modification of the `processRoadname` function at about `line 757` in `map.js`

Revise function to identify strings that should be converted to all caps. 
- NB, SB, EB, WB
- US, PA, NJ
- any others?

**Comment by wtsay** [comment]
Possibly CR, SR

Would it just be better to ~~pass the buck~~ fix the issue at the source (ie. the database)?

There's also empty parenthesis floating around. Like rec. num. 101232

**Comment by crvanpollard** [comment]
place where there are apostrophes ( ' )
<img width="223" alt="screen shot 2016-03-30 at 3 05 11 pm" src="https://cloud.githubusercontent.com/assets/4401281/14154127/ebb3da92-f688-11e5-8d9f-e5d526adb4a2.png">

**Comment by crvanpollard** [comment]
@wtsay the whole database is in lowercase so we can't go and fix the source
