### ISSUE TITLE
Create functionality to download a zip of multiple records

### ISSUE THREAD

**Issue by DVRPCfreight** [DVRPCfreight/TrafficCountConcept#7]
Add:
- [x] Radio functionality to populate list of selected records
- [x] New tab to view selected records 
- [x] Build zip of PDFs for download

**Comment by crvanpollard** [comment]
Add: Create a downloadable CSV of selected records which would include all fields that are part of the ArcGIS Server Feature Service [Set Date/Year, Road Name, Type, DVRPC File Number, Count Direction, Lat, Long, MCD, County, From and To Limit)

**Comment by crvanpollard** [comment]
Let's try and getting something to test with this functionality soon @DVRPCfreight

**Comment by DVRPCfreight** [comment]
Currently working on implementation of this in [DVRPCfreight/TrafficCountConcept/test/ruane-download](/DVRPCfreight/TrafficCountConcept/tree/test/ruane-download). See ea78e357eb919459f3477ffd99b07d08dba3b3cf for initial data saving and parsing. 

In order to zip files, we will need to work with Jesse to get server-side functionality to compile pdf and server .zip.

**Comment by DVRPCfreight** [comment]
@jstrangfeld Any thoughts on creating a zip file server side using JSON and CSV created client side and PDF reports based on the record report URLs

**Comment by jstrangfeld** [comment]
We will soon have .NET 4.5 so any DLL that we can just drop in bin on the server will work. I'm thinking DotNetZip should be simple to use. Just upload the JSON to the server and it will send back a ZIP of CSV files.

Can you give me a little info on what a PDF would be like? Building a PDF programmatically is often pretty tedious.

**Comment by jstrangfeld** [comment]
The ZIP file will contain:
- PDF with each record on a page (from existing Crystal Reports)
- GEOJSON of data from tc_header
- CSV of same data without geodata

Request the file for download like so: http://www.dvrpc.org/asp/trafficCount/download.aspx?recnum= [comma-separated recordnums]

**Comment by wtsay** [comment]
https://github.com/DVRPCfreight/TrafficCountConcept/issues/7#issuecomment-165591243

https://github.com/DVRPCfreight/TrafficCountConcept/commit/801f0df4fa2ad5f166605dfc5909704b94d532d8

Demo:
http://wololo.co/TCC_801f0df/

Edit:
Currently only the fields within the table. Should be trivial to add in the rest of the fields.

**Comment by wtsay** [comment]
Now with more fields!

Demo: 
http://wololo.co/TCC_0fedd4a/

**Comment by crvanpollard** [comment]
Bonzi Buddy Warez needs a lookup table for those MCD values..
<img width="622" alt="screen shot 2016-04-18 at 2 38 19 pm" src="https://cloud.githubusercontent.com/assets/4401281/14615376/58a9cf96-0573-11e6-8731-56ba4bcf72e2.png">

**Comment by DVRPCfreight** [comment]
@crvanpollard @wtsay you guys know that the `data_csv` variable is constructed each time the "view selected records" button is clicked?

Also, is the idea to let them download all results that are returned or just those they select from the table or (since js can be made to do what ever we want) both of these options. Think we need to clarify before continuing implementation. 

@jstrangfeld are you working on a server side implementation for this, including zipped download of csv and pdfs?

**Comment by jstrangfeld** [comment]
@DVRPCfreight I will create the download script for this feature.

@crvanpollard What's the timeline for getting this all together? Pretty busy right now but I want to schedule it in so I don't hold everything up.

**Comment by crvanpollard** [comment]
@jstrangfeld next Tuesday is Alpha Launch. It need to have some sort of export to CSV to match what is in the current app. 
Not sure how important the 'View Selected Records' function/button is since users can filter and draw specific areas and narrow down their results...

With that said, if it's easy to use js to allow the download off all records as well as those that are selected, I say build both since you are all JavaScript Wizards

**Comment by jstrangfeld** [comment]
I can provide access to the ZIP file download (bullet 3 in OP) by Friday or Monday at the latest.

**Comment by crvanpollard** [comment]
@jstrangfeld we will be pushing a few changes to Master soon (fixed a few issues as well as layout changes)

**Comment by jstrangfeld** [comment]
The download script is up and running. It downloads PDFs from the database, Crosswalk, Turning Movements, and Manual Class. It also downloads a CSV of the data from the tc_header table.

Example: http://www.dvrpc.org/asp/trafficCount/download.aspx?recnum=118357,118352,118552,120941,99962

**Comment by crvanpollard** [comment]
@DVRPCfreight after you finish the current Pull request changes can you bake/merge this download function into Master? I will wrap up my changes tomorrow and we should make our Alpha launch date (or be a day or two behind) depending on any issues or merge conflicts

**Comment by DVRPCfreight** [comment]
@jstrangfeld could you please confirm the max size for GET requests on our server. We will probably have to set a maximum number of records per download to stay within the URL limit

**Comment by DVRPCfreight** [comment]
@jstrangfeld are we able to expand the csv to include the other header data? Including LAT, LONG

**Comment by crvanpollard** [comment]
@jstrangfeld For the CSV use the same fields that @wtsay used in his demo from above:
http://wololo.co/TCC_0fedd4a/

DATE,ROAD,COUNTTYPE,AADT,MCD,COUNTY,FROMLIMIT,TOLIMIT,LATITUDE,LONGITUDE,RECORDNUM,SOURCE (This should be DVRPC for all counts).

We also need to add in MCD Names.. Sean has an MCD lookup file here: https://github.com/seandoesgis/TrafficCountETL/blob/master/MCD_LIST.csv

**Comment by jstrangfeld** [comment]
The max URL size for GET requests is 216 characters. We can get around that limitation using POST instead.

Do we need GeoJSON as well?

**Comment by DVRPCfreight** [comment]
@jstrangfeld i think we can get away with just the csv since it contains the lat long
