### ISSUE TITLE
SEO, METADATA, Analytics

### ISSUE THREAD

**Issue by DVRPCfreight** [DVRPCfreight/TrafficCountConcept#83]
**Add GA script code**
**Add the following metadata:**
- [x] Description
- [x] OG:tags
- [x] Twitter cards?

@crvanpollard do you have description for the app?
@jstrangfeld are we doing twitter cards metadata? It allows some more advanced elements that og does not cover.

**Comment by jstrangfeld** [comment]
@DVRPCfreight Go ahead, I'm not going to say no!
