### ISSUE TITLE
Your counts are SLOW

### ISSUE THREAD

**Issue by DVRPCfreight** [DVRPCfreight/TrafficCountConcept#88]
sean fix it. FEMA Sucks

**Comment by crvanpollard** [comment]
#notmycounts

**Comment by crvanpollard** [comment]
@DVRPCfreight when you say SLOW what does this refer to and thoughts on best solutions? 
@rbeatty1 @mmolta @seandoesgis

**Comment by DVRPCfreight** [comment]
@gfred3rick is hand delivering the responses, which has resulted in a poor load time.

@crvanpollard this issue was a joke during the Github training we did. I do not believe there are any issues with the speed of the counts. Closing issue.
