### ISSUE TITLE
Update traffic count GIS service

### ISSUE THREAD

**Issue by seandoesgis** [DVRPCfreight/TrafficCountConcept#90]
Update the traffic count AGO service to read from https://services1.arcgis.com/LWtWv6q6BJyKidj8/arcgis/rest/services/DVRPC_Traffic_Counts/FeatureServer

Also update the access data button
![screen shot 2018-07-27 at 11 48 42 am](https://user-images.githubusercontent.com/16228607/43331136-11bd47e4-9193-11e8-8d4b-bf6826c478fc.png)

ArcGIS Desktop - data can be accessed using https://services1.arcgis.com/LWtWv6q6BJyKidj8/arcgis/

but maybe we drop that all together and maybe just include text to search the data on AGO for desktop gis?  thoughts?

**Comment by crvanpollard** [comment]
URL for Map Service Access has been updated
